package api

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/ArtyomRytikov/posts-comments-service/internal/api/generated"
	"github.com/ArtyomRytikov/posts-comments-service/internal/api/model"
	"github.com/ArtyomRytikov/posts-comments-service/internal/pagination"
)

// Replies is the resolver for the replies field.
func (r *commentResolver) Replies(ctx context.Context, obj *model.Comment, first int, after *string) (*model.CommentConnection, error) {
	postID, err := parseID(obj.PostID)
	if err != nil {
		return nil, err
	}
	parentID, err := parseID(obj.ID)
	if err != nil {
		return nil, err
	}
	return loadComments(ctx, postID, parentID, false, first, after)
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	post, err := r.service.CreatePost(ctx, actor(ctx), input.Title, input.Body, input.CommentsEnabled)
	if err != nil {
		return nil, err
	}
	return postModel(post), nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.CreateCommentInput) (*model.Comment, error) {
	postID, err := parseID(input.PostID)
	if err != nil {
		return nil, err
	}
	var parentID int64
	if input.ParentID != nil {
		parentID, err = parseID(*input.ParentID)
		if err != nil {
			return nil, err
		}
	}
	comment, err := r.service.CreateComment(ctx, actor(ctx), postID, parentID, input.Body)
	if err != nil {
		return nil, err
	}
	return commentModel(comment), nil
}

// SetCommentsEnabled is the resolver for the setCommentsEnabled field.
func (r *mutationResolver) SetCommentsEnabled(ctx context.Context, postID string, enabled bool) (*model.Post, error) {
	id, err := parseID(postID)
	if err != nil {
		return nil, err
	}
	post, err := r.service.SetCommentsEnabled(ctx, id, actor(ctx), enabled)
	if err != nil {
		return nil, err
	}
	return postModel(post), nil
}

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *model.Post, first int, after *string) (*model.CommentConnection, error) {
	id, err := parseID(obj.ID)
	if err != nil {
		return nil, err
	}
	return loadComments(ctx, id, 0, false, first, after)
}

// CommentFeed is the resolver for the commentFeed field.
func (r *postResolver) CommentFeed(ctx context.Context, obj *model.Post, first int, after *string) (*model.CommentConnection, error) {
	id, err := parseID(obj.ID)
	if err != nil {
		return nil, err
	}
	return loadComments(ctx, id, 0, true, first, after)
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, first int, after *string) (*model.PostConnection, error) {
	page, err := pagination.Page(first, optionalString(after), pagination.PostsScope)
	if err != nil {
		return nil, err
	}
	posts, err := r.service.Posts(ctx, page)
	if err != nil {
		return nil, err
	}
	return postConnection(posts), nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	postID, err := parseID(id)
	if err != nil {
		return nil, err
	}
	post, err := r.service.GetPost(ctx, postID)
	if err != nil {
		return nil, err
	}
	return postModel(post), nil
}

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID string) (<-chan *model.Comment, error) {
	id, err := parseID(postID)
	if err != nil {
		return nil, err
	}
	stream, err := r.service.Subscribe(ctx, id)
	if err != nil {
		return nil, err
	}
	out := make(chan *model.Comment)
	go func() {
		defer close(out)
		for {
			select {
			case <-ctx.Done():
				return
			case comment, ok := <-stream:
				if !ok {
					return
				}
				select {
				case out <- commentModel(comment):
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return out, nil
}

// Comment returns generated.CommentResolver implementation.
func (r *Resolver) Comment() generated.CommentResolver { return &commentResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Post returns generated.PostResolver implementation.
func (r *Resolver) Post() generated.PostResolver { return &postResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type commentResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
