// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Comment struct {
	ID        string    `json:"id"`
	PostID    string    `json:"postID"`
	ParentID  *string   `json:"parentID,omitempty"`
	AuthorID  string    `json:"authorID"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"createdAt"`
	// Immediate replies. Storage supports arbitrary depth; query depth is bounded.
	Replies *CommentConnection `json:"replies"`
}

type CommentConnection struct {
	Edges    []*CommentEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type CommentEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Comment `json:"node"`
}

type CreateCommentInput struct {
	PostID string `json:"postID"`
	// Omit for a root comment. The parent must belong to the same post.
	ParentID *string `json:"parentID,omitempty"`
	// At most 2000 Unicode characters.
	Body string `json:"body"`
}

type CreatePostInput struct {
	Title           string `json:"title"`
	Body            string `json:"body"`
	CommentsEnabled bool   `json:"commentsEnabled"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type Post struct {
	ID              string    `json:"id"`
	AuthorID        string    `json:"authorID"`
	Title           string    `json:"title"`
	Body            string    `json:"body"`
	CommentsEnabled bool      `json:"commentsEnabled"`
	CreatedAt       time.Time `json:"createdAt"`
	// Root comments only, in ascending creation ID order.
	Comments *CommentConnection `json:"comments"`
	// All comments, including replies, with parentID for iterative tree building.
	CommentFeed *CommentConnection `json:"commentFeed"`
}

type PostConnection struct {
	Edges    []*PostEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type PostEdge struct {
	Cursor string `json:"cursor"`
	Node   *Post  `json:"node"`
}

type Query struct {
}

type Subscription struct {
}
